services:
  api:
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://dick_user:mysecretpassword@db:5432/dick_data
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: dick_data
      POSTGRES_USER: dick_user
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local