CREATE TABLE IF NOT EXISTS dicks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    guild_id TEXT NOT NULL,
    length INTEGER NOT NULL DEFAULT 0,
    last_grow TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    growth_count INTEGER NOT NULL DEFAULT 0,
    dick_of_day_count INTEGER NOT NULL DEFAULT 0,
    pvp_wins INTEGER NOT NULL DEFAULT 0,
    pvp_losses INTEGER NOT NULL DEFAULT 0,
    pvp_max_streak INTEGER NOT NULL DEFAULT 0,
    pvp_current_streak INTEGER NOT NULL DEFAULT 0,
    cm_won INTEGER NOT NULL DEFAULT 0,
    cm_lost INTEGER NOT NULL DEFAULT 0,
    UNIQUE(user_id, guild_id)
);

CREATE TABLE IF NOT EXISTS guild_settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    guild_id TEXT NOT NULL UNIQUE,
    last_dotd TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);